# Generated by Django 3.2.9 on 2021-11-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0004_auto_20211112_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_balance',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', unique=True),
        ),
    ]
